general {
    lock_cmd = dot-lock                                  # lock screen
    before_sleep_cmd = DOT_LOCK_ONLY=true dot-lock       # lock before suspend
    after_sleep_cmd = sleep 1 && hyprctl dispatch dpms on
    inhibit_sleep = 3                                    # wait until screen is locked
}

# Lock after 5 minutes
listener {
    timeout = 300
    on-timeout = dot-lock
    on-resume = hyprctl dispatch dpms on
}
